server:
  port: 9801

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false #用于表明自己是一个Server
    fetchRegistry: false #用于表明自己是一个Server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 2000